### ISSUE TITLE
Not informative 'Unable to locate the element' message

### ISSUE THREAD

**Issue by yashaka** [yandex-qatools/htmlelements#46]
If the element could not be find by locator (in the chromedriver case at least), The following exception is thrown:

```
org.openqa.selenium.NoSuchElementException: Timed out after 5 seconds. Unable to locate the element
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.31.0', revision: '1bd294d185a80fa4206dfeab80ba773c04ac33c0', time: '2013-02-27 13:51:26'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.8.0-27-generic', java.version: '1.7.0_25'
Driver info: driver.version: unknown
    at ru.yandex.qatools.htmlelements.pagefactory.AjaxElementLocator.findElement(AjaxElementLocator.java:73)
    at ru.yandex.qatools.htmlelements.loader.decorator.proxyhandlers.WebElementNamedProxyHandler.invoke(WebElementNamedProxyHandler.java:29)
    at com.sun.proxy.$Proxy11.isDisplayed(Unknown Source)
    at com.swisscom.stargate.staf.webui.PagesContentStaticTest.assertPageExpectedElementsAreDisplayed(PagesContentStaticTest.java:45)
```

Why not add additional info about the element (annotated with @FindBy) which was not find? At least something to identify it from the test result... The variable name, locator (xpath, css used in FindBy, etc.), etc...

**Comment by lanwen** [comment]
Will be added cause info with selector in #75. Can i close this issue for now?
