### ISSUE TITLE
StaleElementReferenceException when we use HasAttributeMatcher

### ISSUE THREAD

**Issue by emaks** [yandex-qatools/htmlelements#85]
sometimes I get error

```
StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=43.0.2357.124)
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 48 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'Sellenium', ip: '78.140.165.48', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\admin\AppData\Local\Temp\scoped_dir3248_9756}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=43.0.2357.124, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 6f9beb95fe74f48ef2f3921c7a33c361
Command duration or timeout: 234 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'cinode2.club-vulkan.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-042stab103.6', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\admin\AppData\Local\Temp\scoped_dir3248_9756}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=43.0.2357.124, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=7a395577-ec73-453f-8a10-d84ee739014b, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 7a395577-ec73-453f-8a10-d84ee739014b
org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=43.0.2357.124)
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 48 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'Sellenium', ip: '78.140.165.48', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\admin\AppData\Local\Temp\scoped_dir3248_9756}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=43.0.2357.124, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 6f9beb95fe74f48ef2f3921c7a33c361
Command duration or timeout: 234 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'cinode2.club-vulkan.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-042stab103.6', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\admin\AppData\Local\Temp\scoped_dir3248_9756}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=43.0.2357.124, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=7a395577-ec73-453f-8a10-d84ee739014b, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 7a395577-ec73-453f-8a10-d84ee739014b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:269)
	at org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:123)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at ru.yandex.qatools.htmlelements.loader.decorator.proxyhandlers.WebElementNamedProxyHandler.invoke(WebElementNamedProxyHandler.java:36)
	at com.sun.proxy.$Proxy18.getAttribute(Unknown Source)
	at ru.yandex.qatools.htmlelements.element.HtmlElement.getAttribute(HtmlElement.java:141)
	at ru.yandex.qatools.htmlelements.matchers.common.HasAttributeMatcher.matchesSafely(HasAttributeMatcher.java:28)
	at ru.yandex.qatools.htmlelements.matchers.common.HasAttributeMatcher.matchesSafely(HasAttributeMatcher.java:17)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at ru.yandex.qatools.htmlelements.matchers.decorators.WaiterMatcherDecorator.matchesSafely(WaiterMatcherDecorator.java:26)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at ru.yandex.qatools.htmlelements.matchers.decorators.MatcherDecoratorsBuilder.matchesSafely(MatcherDecoratorsBuilder.java:30)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
```

Problem [in] (https://github.com/yandex-qatools/htmlelements/blob/master/htmlelements-matchers/src/main/java/ru/yandex/qatools/htmlelements/matchers/common/HasAttributeMatcher.java#L28)

I guess we need to use 
```
        try {
            return attributeValueMatcher.matches(item.getAttribute(attributeName));
        } catch (WebDriverException e) {
            return false;
        }

**Comment by aik099** [comment]
You'll get stale element exception in following scenario:

1. search for element on the page (element is really on the page)
2. something happens on the page, that causes element to be removed (e.g. ajax request)
3. the element reference found before is used to act on element (e.g. click on it)
4. element isn't there and exception is thrown

**Comment by artkoshelev** [comment]
Throwing assertion error means there is a bug in application. Throwing any kind of exception means the test is broken. So it's absolutely correct behavior.
