### ISSUE TITLE
ParameterizedTypeImpl cannot be cast to java.lang.Class - HtmlElementDecorator issue

### ISSUE THREAD

**Issue by ham1** [yandex-qatools/htmlelements#94]
This seems related to #78 and #80.

The Table implementation is very slow (it takes about 30s in Firefox for this table https://en.wikipedia.org/wiki/List_of_highest_mountains), as such, I wanted to cache the output of ```getRowsAsString()``` as we often do multiple checks on the same data (we can be sure that no other operation will happen on the table to change it, and, if needs be, we can easily clear the cache).

My page object looks like:

```java
    @FindBy(css = "table") // luckily there's only one
    private Table listTable;

    private List<List<String>> rows; // rows cache

    public String getRankByName(String name) {
        return getRowByName(name).get(0);
    }

    public String getHeightInFeetByName(String name) {
        return getRowByName(name).get(3);
    }

    private List<String> getRowByName(String name) {
        return getRowStream()
                .filter(row -> row.get(1).contains(name)) // find by name
                .findFirst() // find the first one if it exists
                .get(); // get the row, will throw exception if not found
    }

    private Stream<List<String>> getRowStream() {
        if (null == rows) {
            rows = listTable.getRowsAsString();
        }
        return rows.stream()
                .filter(row -> row.size() > 2);  // make sure we have columns
    }
```

However I get the following stack trace with the latest master of htmlelements.

```
sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at ru.yandex.qatools.htmlelements.utils.HtmlElementUtils.getGenericParameterClass(HtmlElementUtils.java:95) ~[classes/:?]
	at ru.yandex.qatools.htmlelements.utils.HtmlElementUtils.isTypifiedElementList(HtmlElementUtils.java:81) ~[classes/:?]
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementDecorator.decorate(HtmlElementDecorator.java:62) ~[classes/:?]
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113) ~[selenium-support-2.48.2.jar:?]
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105) ~[selenium-support-2.48.2.jar:?]
	at ru.yandex.qatools.htmlelements.loader.HtmlElementLoader.populatePageObject(HtmlElementLoader.java:251) ~[classes/:?]
	at ru.yandex.qatools.htmlelements.loader.HtmlElementLoader.populatePageObject(HtmlElementLoader.java:241) ~[classes/:?]
```
Is there something that could be done to allow this? e.g. an ```@Ignore``` annotation, or only parsing paramaritised lists of WebElements?

**Comment by artkoshelev** [comment]
Can you make a pull-request with a simple failing unit-test demonstrating your problem?
